### ISSUE TITLE
Syntax For Timing - Is it correct?

### ISSUE THREAD

**Issue by Biscuit170** [baconator696/Recu-Download#2]
Heya - so you've suggested the syntax as follows for time-specific parts of videos, but cant get it to work

![image](https://github.com/baconator696/Recu-Download/assets/134964275/6198e7a5-554d-4245-bdf7-9497d7c2b70f)

so that was suggestion, but program immediately closes - does having that 2nd curved bracket not close off the first opening one? I tried a double bracket curved but couldnt get it to work.

![image](https://github.com/baconator696/Recu-Download/assets/134964275/92f7b27f-ba7d-474f-aaaa-81ebdbb91ab1)

Whatever im doing isnt working, but hoping you can elaborate on the bracket syntax

For 2nd point - i seem to get timeout also which cuts the DL - worked fine literally yesterday for testing on about 12min video, but today having a not as good time:

![image](https://github.com/baconator696/Recu-Download/assets/134964275/55a75538-315b-40fd-8302-92c15f4adbd8)

Cheers!

**Comment by baconator696** [comment]
this formatting is for the [v1.11.0-pre](https://github.com/baconator696/Recu-Download/releases/tag/v1.11.0-pre) version, so make sure you have that downloaded

your json format is wrong, here is revised version:
```JSON
{
	"urls": [
		["https://recu.me/video/*********/play","3:00:00","3:30:00","4:29:16"]
	],
	"header": {
		"Cookie": "",
		"User-Agent": ""
	}
}
```

on the second point, it is because you aren't signed into recu.me

also your should use a different terminal since yours doesn't support ANSI escape codes, you'll have a better user experience
